# name: Echo Practice by apo1798
# run-name: ${{ github.actor }} is greeting

# on: [push]
# jobs:
#   echo-action:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Echo Practice by apo1798
#         uses: apo1798/echo-action@1.0
#         with:
#           user: ${{ github.actor }}

#  ///////////////////////////////////

# name: Using HongLinLiao echo-action
# run-name: ${{ github.actor }} is greeting

on: [push]
jobs:
  call-apo1798-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Practice by apo1798
        uses: apo1798/echo-action@a4cb21017013701ac4ae47e60328c16c0cef75ef
        # uses: apo1798/echo-action@main
        with:
          user: ${{ github.actor }}
